---
name: "ges"

deploymentConfig:
  quickMode: true

runtimes:
  - name: main
    routes: []

    subscriptions:
      - name: "global/event"
      - name: "global/upsert"

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: ges
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: LOG_LEVEL
            value: "debug"

          - name: POSTGRES_URL
            database:
              databaseName: main

          - name: GRPC_PORT
            value: "8080"

