---
name: "ges"

deploymentConfig:
  quickMode: true

databases:
  - name: main
    postgres:
      runOutbox: true
      serverGroup: default
      dbExtensions:
        - "uuid-ossp"

      migrateContainer:
        image:
          name: ges
          registry: ghcr.io/pentops
        command: [migrate]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main

runtimes:
  - name: main
    routes: 
      - prefix: "/ges/v1"
        protocol: ROUTE_PROTOCOL_HTTP

    subscriptions:
      - name: "global/event"
        envName: "*"
      - name: "global/upsert"
        envName: "*"

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: ges
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: LOG_LEVEL
            value: "debug"

          - name: POSTGRES_URL
            database:
              databaseName: main

          - name: GRPC_BIND
            value: ":8080"

